### ISSUE TITLE
MobilePay Subscriptions

### ISSUE THREAD

**Issue by DybH** [QuickPay/whmcs-module#3]
MobilePay Subscriptions, dosen't seem to work properly using QuickPay Module.

**Comment by Mathias-Skov** [comment]
Yea my MobilePay Subscriptions doesn't work either.

The callback returns: "Quickpay payment response: {"message":"Validation failed","data":null,"errors":{"auto_capture_at":["must be at least 2 days in the future"]}}" even when the autocapture is set to 0.

The subscription itself seems to be active, but the callback doesn't work properly.
